[project]
name = "my_env"
version = "0.1.0"
requires-python = "==3.10.*"
dependencies = [
  "numpy==1.26.4",
  "scipy==1.15.3",
  "transformers==4.57.1",
  "wandb==0.22.1",
  "natsort==8.4.0",
  "cairosvg==2.8.2",
  "requests==2.32.5",
  "urllib3==2.5.0",
  "protobuf==3.20.3",
  "svgpathtools==1.7.1",
  "torch==2.7.1",
  "torchvision==0.22.1",
  "torchaudio==2.7.1",
  "omegaconf==2.3.0",
  "matplotlib==3.10.7",
  "diffusers==0.36.0",
]

[project.optional-dependencies]
dev = [
  "ruff==0.14.7",
  "ipykernel==7.1.0",
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.setuptools.packages.find]
where = ["src"]